name: Build and Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# Add permissions for GitHub Actions
permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint

      - name: Check Prettier formatting
        run: npm run format:check

      - name: Build Astro site
        run: npm run build

      - name: Test build output
        run: |
          echo "✓ Build completed successfully!"
          ls -la dist/
          test -f dist/index.html && echo "✓ index.html found" || exit 1
          echo "✓ Ready for deployment"

      # Add a comment to PR with build status (with error handling)
      - name: Comment on PR
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            try {
              await github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: '✅ Build completed successfully! Preview deployment should be available shortly on Cloudflare Pages.'
              })
            } catch (error) {
              console.log('Could not comment on PR:', error.message)
              // Don't fail the workflow if commenting fails
            }
